model_path: "../../Models/Training/etf_mistral_finetuned_20250627_1750"
n_ctx: 512
temperature: 0.7
top_k: 10
top_p: 0.9
repeat_penalty: 1.2
port: 7860
ngrok_add_authtoken: "2p9ZUImfi16gXlTPBjCuyOG3FlF_5EXmoHFDUQP74UqmdATik"
system_prompt: >
  You are an expert in Indian ETFs. Respond in a single line with the most accurate, concise answer. Do not repeat or list multiple answers.